const PDFDocument = require("pdfkit");
const Case = require("../models/Case");
const Evidence = require("../models/Evidence");
const CustodyLog = require("../models/CustodyLog");

exports.generateReport = async (req, res) => {
  try {
    const caseId = req.params.id;

    const caseData = await Case.findById(caseId);
    const evidences = await Evidence.find({ caseId });

    if (!caseData) {
      return res.status(404).json("Case not found");
    }

    // ✅ FIX: only logs for this case
    const evidenceIds = evidences.map(e => String(e._id));

    const logs = await CustodyLog.find({
      evidenceId: { $in: evidenceIds }
    }).sort({ timestamp: 1 });

    const doc = new PDFDocument({ margin: 50 });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename=case-${caseId}.pdf`
    );

    doc.pipe(res);

    // 🏛 HEADER
    doc.fontSize(22).text("DIGITAL FORENSIC REPORT", { align: "center" });
    doc.fontSize(10).text("Secure Evidence Management System", { align: "center" });

    doc.moveDown(2);

    // 📁 CASE DETAILS
    doc.fontSize(16).text("Case Details", { underline: true });
    doc.moveDown();

    doc.fontSize(12);
    doc.text(`Title: ${caseData.title}`);
    doc.text(`Crime Type: ${caseData.crimeType || "N/A"}`);
    doc.text(`Location: ${caseData.location || "N/A"}`);
    doc.text(`Status: ${caseData.status}`);
    doc.text(`Created: ${new Date(caseData.createdAt).toLocaleString()}`);

    doc.moveDown();

    // 📦 EVIDENCE SECTION
    doc.fontSize(16).text("Evidence Details", { underline: true });
    doc.moveDown();

    evidences.forEach((e, i) => {
      const status = e.verificationStatus || "NOT VERIFIED";

      doc.fontSize(12).text(`Evidence ${i + 1}`);
      doc.text(`File: ${e.fileName}`);
      doc.text(`Hash: ${e.hashValue}`);
      doc.text(`Status: ${status}`);
      doc.text(`Tx Hash: ${e.txHash || "N/A"}`);
      doc.text(`Block Number: ${e.blockNumber || "N/A"}`);

 if (e.txHash) {

  const blockchainUrl =
    `https://sepolia.etherscan.io/tx/${e.txHash}`;

  doc
    .fillColor("blue")
    .text(
      "View on Blockchain",
      {
        link: blockchainUrl,
        underline: true
      }
    );

  doc
    .fillColor("black");

  doc.text(blockchainUrl);
}

      doc.text(`Uploaded: ${new Date(e.uploadedAt).toLocaleString()}`);

      doc.moveDown();
    });

    // 📊 TIMELINE
    doc.addPage();

    doc.fontSize(16).text("Chain of Custody Timeline", { underline: true });
    doc.moveDown();

    logs.forEach((log, i) => {
      doc.fontSize(12).text(
        `${i + 1}. ${log.action} by User ${log.userId}`
      );
      doc.text(`Time: ${new Date(log.timestamp).toLocaleString()}`);
      doc.moveDown();
    });

    // 🏁 FOOTER
    doc.moveDown(2);
    doc.fontSize(10).text(
      "Generated by Digital Evidence System | Blockchain Secured",
      { align: "center" }
    );

    doc.end();

  } catch (err) {
    console.error(err);
    res.status(500).json("Error generating report");
  }
};